# example netlify.toml
[build]
  command = "quasar build"
  functions = "netlify/functions"
  publish = "dist/spa"

## Uncomment to use this redirect for Single Page Applications
## Not needed for static site generators.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
